import { z } from 'zod';
import type { PointsLive } from './points';
import type { FlyAppearance } from './appearance';
import type { UserRole } from './user';
import { FLY_COLOR_IDS } from './appearance';
export * from './appearance';
export * from './presence';
export * from './user';
export const flyAppearanceSchema = z
  .object({
    eyes: z.enum(FLY_COLOR_IDS).default('natural'),
    body: z.enum(FLY_COLOR_IDS).default('natural'),
    wings: z.enum(FLY_COLOR_IDS).default('natural'),
  })
  .strict();
export type Vec3 = [number, number, number];
export type Quat = [number, number, number, number];
export type SimulationMode = 'flywire' | 'offline';
export type FlyFoodPreference = 'apple' | 'pear' | 'berry';
export interface FlyPersonality {
  /** Stable server-generated traits. Users never choose or submit these values. */
  curiosity: number;
  sociability: number;
  boldness: number;
  activity: number;
  flightAffinity: number;
  favoriteFood: FlyFoodPreference;
}
export type FlyIntentKind = 'eat' | 'drink' | 'explore' | 'socialize' | 'avoid' | 'rest' | 'groom';
export type FlyIntentStage = 'notice' | 'travel' | 'act' | 'recover';
export interface FlyIntent {
  kind: FlyIntentKind;
  stage: FlyIntentStage;
  startedAt: number;
  stageStartedAt: number;
  targetId?: string;
  targetName?: string;
  targetPosition?: Vec3;
}
export interface FlyRelationship {
  id: string;
  flyAId: string;
  flyBId: string;
  familiarity: number;
  affinity: number;
  encounters: number;
  together: number;
  followed: number;
  avoided: number;
  firstMetAt: number;
  lastInteractionAt: number;
  /** Deduplicates the symmetric observations emitted by two nearby flies. */
  lastSignal?: EventType;
}
export interface CompanionBrainTelemetry {
  available: boolean;
  deviceId: string;
  deviceLabel: string;
  updatedAt: number;
  tick: number;
  neurons: number;
  edges: number;
  fired: number;
  tickMs: number;
  forward: number;
  turn: number;
  /** FlyWire activity for the 63 groups rendered by the browser brain view. */
  groups: number[];
}
export type OfflineAction =
  | 'rest'
  | 'groom'
  | 'weather'
  | 'walk'
  | 'flight'
  | 'seekFood'
  | 'seekWater'
  | 'eat'
  | 'drink'
  | 'social'
  | 'avoid'
  | 'escape';
export type BodyBehavior =
  'WALK' | 'IDLE' | 'GROOM' | 'FEED' | 'ALERT' | 'TAKEOFF' | 'FLIGHT' | 'LAND';
export type GroomingTarget = 'legs' | 'head' | 'antennae' | 'wings' | 'abdomen';
/** Observable, temporary posture. Neural traces never cross the network. */
export interface BodyPose {
  behavior: BodyBehavior;
  flight: 'ground' | 'preparing' | 'airborne' | 'landing';
  phase: number;
  intensity: number;
  groomingTarget: GroomingTarget;
  legs: number;
  wings: number;
  headYaw: number;
  headPitch: number;
  antennaLeft: number;
  antennaRight: number;
  proboscis: number;
  pitch: number;
  roll: number;
}
export interface FlyIdentity {
  flyId: string;
  ownerId: string;
  name: string;
  createdAt: number;
  /** Cosmetic identity chosen at adoption. Legacy flies use the natural palette. */
  appearance?: FlyAppearance;
  /** Immutable random-looking temperament generated by the server from this identity. */
  personality?: FlyPersonality;
}
export interface FlyState extends FlyIdentity {
  intervention?: import('./shop').Purchase;
  rewardSuppressedUntil?: number;
  /** Server-owned bodily needs; legacy saves are initialized on load. */
  /** Food and hydration satisfaction reserves, both on a 0–100 scale. */
  needs?: { hunger: number; hydration: number; updatedAt: number; scale?: 'food' };
  /** Permanent, server-owned end of this life. Absence means alive (legacy compatible). */
  death?: { at: number; cause: 'hunter'; hunterId: string } | { at: number; cause: 'exhaustion' };
  position: Vec3;
  velocity: Vec3;
  rotation: Quat;
  timestamp: number;
  lastSeenAt: number;
  /** Derived by the server: food satisfaction × 50% + hydration × 50%. */
  energy: number;
  /** Last accepted drink; server-owned and persisted across reconnects. */
  lastDrankAt?: number;
  connected: boolean;
  /** A consenting visitor is temporarily running this fly's browser brain. */
  hosted?: boolean;
  /** A linked companion device has checked in recently. It does not own the simulation. */
  companionConnected?: boolean;
  /** Last authenticated companion-device heartbeat, in Unix milliseconds. */
  companionLastSeenAt?: number;
  /** Recent neural telemetry reported by the linked companion device. */
  companionBrain?: CompanionBrainTelemetry;
  mode: SimulationMode;
  totalLifeTime: number;
  status: string;
  /** Current autonomous multi-step motivation, selected by the simulation. */
  intent?: FlyIntent;
  body?: BodyPose;
  /** Compact server hint used only to animate approximate offline activity. */
  offlineAction?: OfflineAction;
  /** Small, bounded spatial memory used by both live senses and offline approximation. */
  habitatMemory?: {
    food?: { position: Vec3; updatedAt: number; foodKind?: string };
    water?: { position: Vec3; updatedAt: number };
    rest?: { position: Vec3; updatedAt: number };
    danger?: { position: Vec3; updatedAt: number };
    groomingStep?: number;
  };
  /** Private owner checkpoint; excluded from public world snapshots. */
  bodyMemory?: { savedAt: number; agedAt?: number; value: BodyMemory };
  /** Server-owned history, excluded from shared snapshots and owner sockets. */
  dashboardHistory?: EnergyHistory;
}

export interface EnergyPoint {
  timestamp: number;
  value: number;
  mode: SimulationMode | 'mixed';
}
export interface EnergyHistory {
  since: number;
  samples: EnergyPoint[];
  daily: { day: string; sum: number; count: number; min: number; max: number }[];
}
export type DashboardRange = 'all' | '24h' | '7d';
export type DashboardCategory =
  'all' | 'food' | 'social' | 'flight' | 'care' | 'exploration' | 'session';
export interface FlyDashboard {
  needs?: FlyState['needs'];
  death?: FlyState['death'];
  /** Whole-life summary, independent of dashboard filters; absent for living flies. */
  endOfLife?: {
    lifetimeSeconds: number;
    hunterAttempts: number;
    hunterEscapes: number;
    mode: SimulationMode | null;
  };
  flyId: string;
  name: string;
  updatedAt: number;
  createdAt: number;
  totalLifeTime: number;
  energy: number;
  connected: boolean;
  companionConnected?: boolean;
  status: string;
  personality?: FlyPersonality;
  intent?: FlyIntent;
  range: DashboardRange;
  totals: {
    events: number;
    meals: number;
    drinks: number;
    encounters: number;
    neighbors: number;
    flights: number;
    grooming: number;
    areas: number;
    offline: number;
  };
  foods: { key: string; name: string; count: number }[];
  friends: {
    flyId: string;
    name: string;
    encounters: number;
    together: number;
    followed: number;
    score: number;
    lastSeen: number;
    affinity?: number;
    familiarity?: number;
    relationship?: 'known' | 'friend' | 'best-friend' | 'rival';
  }[];
  activity: {
    timestamp: number;
    food: number;
    social: number;
    flight: number;
    care: number;
    exploration: number;
    session: number;
  }[];
  energyHistory: { since: number | null; points: EnergyPoint[]; averaged: boolean };
  behaviors: Partial<Record<BodyBehavior, number>>;
  history: { events: FlyEvent[]; page: number; pageSize: number; total: number };
}
export type EventType =
  | 'ENTER_WORLD'
  | 'LEAVE_WORLD'
  | 'FOOD_FOUND'
  | 'FOOD_REACHED'
  | 'FOOD_CONSUMED'
  | 'WATER_DRANK'
  | 'FLY_ENCOUNTER'
  | 'LONG_INTERACTION'
  | 'NEW_AREA'
  | 'DANGER'
  | 'HUNTER_ESCAPE'
  | 'DIED'
  | 'RETURN_TO_LOCATION'
  | 'GROOMED'
  | 'TOOK_OFF'
  | 'LANDED'
  | 'FLEW_TO_AREA'
  | 'FOLLOWED_FLY'
  | 'AVOIDED_FLY'
  | 'REACTED_TO_STIMULUS'
  | 'RESTED';
export interface FlyEvent {
  bonuses?: { code: string; points: number; label: string }[];
  reward?: { points: number; rarity: import('./points').Rarity };
  id: string;
  flyId: string;
  type: EventType;
  timestamp: number;
  position: Vec3;
  mode: SimulationMode;
  metadata: Record<string, string | number>;
}
export interface ChatMessage {
  id: string;
  flyId: string;
  flyName: string;
  /** Server-authoritative role captured when the message is published. */
  senderRole?: UserRole;
  text: string;
  timestamp: number;
}
export interface WorldObject {
  id: string;
  type: 'food' | 'water' | 'flower' | 'rock' | 'bush' | 'perch' | 'trunk' | 'zone';
  name: string;
  position: Vec3;
  radius: number;
  amount?: number;
  color?: string;
  height?: number;
  foodKind?: 'apple' | 'pear' | 'berry';
  initialAmount?: number;
  decayRate?: number;
  consumedAmount?: number;
  /** Server time used only to present newly arrived fruit falling into the garden. */
  spawnedAt?: number;
  fallDurationMs?: number;
}
export interface WorldState {
  gardenEvent?: import('./shop').Purchase;
  naturalEvent?: import('./natural-events').NaturalGardenEvent;
  /** Next server-scheduled natural event. Lets clients explain quiet periods. */
  naturalEventNextAt?: number;
  hunter?: HunterState;
  worldId: string;
  objects: WorldObject[];
  flies: FlyState[];
  tick: number;
  timestamp: number;
}

/** Root-level changes to one fly since the previous authoritative snapshot. */
export interface FlyStatePatch {
  flyId: string;
  set: Partial<Omit<FlyState, 'flyId'>>;
  /** Optional properties that disappeared from the authoritative state. */
  unset?: Exclude<keyof FlyState, 'flyId'>[];
}

/**
 * Incremental garden state. A full WorldState is sent once when a client joins;
 * subsequent messages contain only fields that changed.
 */
export interface WorldDelta {
  worldId: string;
  tick: number;
  timestamp: number;
  flies?: FlyStatePatch[];
  addedFlies?: FlyState[];
  removedFlyIds?: string[];
  objects?: WorldObject[];
  removedObjectIds?: string[];
  /** Used by stateless public polling to replace mutable object families. */
  replaceObjectTypes?: WorldObject['type'][];
  gardenEvent?: import('./shop').Purchase | null;
  naturalEvent?: import('./natural-events').NaturalGardenEvent | null;
  naturalEventNextAt?: number | null;
  hunter?: HunterState | null;
}
export interface HunterState {
  id: string;
  name: string;
  position: Vec3;
  velocity: Vec3;
  yaw: number;
  status: 'walking' | 'resting' | 'pouncing';
  timestamp: number;
}
export interface SensoryInput {
  foodTaste?: number;
  waterTaste?: number;
  hunger?: number;
  visionLeft: number;
  visionRight: number;
  odorLeft: number;
  odorRight: number;
  touch: number;
  taste: number;
  light: number;
  wind: number;
  temperature: number;
  socialLeft?: number;
  socialRight?: number;
  socialContactLeft?: number;
  socialContactRight?: number;
  socialNear?: number;
  explorationLeft?: number;
  explorationRight?: number;
  disturbance?: number;
  dangerLeft?: number;
  dangerRight?: number;
  habitatLeft?: number;
  habitatRight?: number;
  lightLeft?: number;
  lightRight?: number;
  windLeft?: number;
  windRight?: number;
  sleepPressure?: number;
  wakefulness?: number;
  heightPreference?: number;
}
export interface NeuralMotorSignals {
  drive: number;
  arousal: number;
  tactile: number;
  wind: number;
  odorLeft: number;
  odorRight: number;
  obstacleLeft: number;
  obstacleRight: number;
  socialLeft?: number;
  socialRight?: number;
  socialContact?: number;
  threat?: number;
  startle?: number;
  sleepPressure?: number;
  heightPreference?: number;
}
export interface MotorOutput {
  forward: number;
  turn: number;
  lift: number;
  feed: number;
  neural?: NeuralMotorSignals;
}
export interface BodyMotorOutput extends MotorOutput {
  lateral: number;
  brake: number;
  pose: BodyPose;
}
export interface NeuralActivity {
  tick: number;
  fired: number;
  neurons: number;
  edges: number;
  tickMs: number;
  groups: number[];
  /** Groups processing stimulation or propagated input, including subthreshold activity. */
  groupActive?: number[];
  motor: MotorOutput;
}
export interface FlyWireBrain {
  initialize(): Promise<void>;
  reset(): void;
  step(input: SensoryInput, dt: number): MotorOutput;
  getActivity(): NeuralActivity;
  dispose(): void;
}
const vector = z.tuple([z.number().finite(), z.number().finite(), z.number().finite()]);
const unit = z.number().finite().min(0).max(1);
const signed = z.number().finite().min(-1).max(1);
const accumulated = z.number().finite().min(0).max(1e9);
const behaviorTotals = z
  .object({
    WALK: accumulated.optional(),
    IDLE: accumulated.optional(),
    GROOM: accumulated.optional(),
    FEED: accumulated.optional(),
    ALERT: accumulated.optional(),
    TAKEOFF: accumulated.optional(),
    FLIGHT: accumulated.optional(),
    LAND: accumulated.optional(),
  })
  .strict();
export const bodyMemorySchema = z
  .object({
    version: z.literal(1),
    time: accumulated,
    fatigue: unit,
    dust: unit,
    satiety: unit,
    flightLoad: unit,
    wingFatigue: unit,
    refractory: z.number().finite().min(0).max(120),
    sequence: accumulated.int(),
    counts: behaviorTotals.refine((v) => Object.values(v).every(Number.isInteger)),
    seconds: behaviorTotals,
  })
  .strict();
export type BodyMemory = z.infer<typeof bodyMemorySchema>;
export const bodyCheckpointSchema = z
  .object({
    type: z.literal('BODY_CHECKPOINT'),
    flyId: z.string().max(80),
    timestamp: z.number().finite(),
    value: bodyMemorySchema,
  })
  .strict();
export const bodyPoseSchema = z
  .object({
    behavior: z.enum(['WALK', 'IDLE', 'GROOM', 'FEED', 'ALERT', 'TAKEOFF', 'FLIGHT', 'LAND']),
    flight: z.enum(['ground', 'preparing', 'airborne', 'landing']),
    phase: unit,
    intensity: unit,
    groomingTarget: z.enum(['legs', 'head', 'antennae', 'wings', 'abdomen']),
    legs: unit,
    wings: unit,
    headYaw: signed,
    headPitch: signed,
    antennaLeft: signed,
    antennaRight: signed,
    proboscis: unit,
    pitch: signed,
    roll: signed,
  })
  .strict();
export const stateMessageSchema = z
  .object({
    type: z.literal('FLY_STATE'),
    flyId: z.string().max(80),
    timestamp: z.number().finite(),
    position: vector,
    velocity: vector,
    rotation: z.tuple([
      z.number().finite(),
      z.number().finite(),
      z.number().finite(),
      z.number().finite(),
    ]),
    body: bodyPoseSchema.optional(),
    path: z.array(vector).min(1).max(16).optional(),
  })
  .strict();
export type StateMessage = z.infer<typeof stateMessageSchema>;
export interface SimulationLease {
  leaseId: string;
  epoch: number;
  expiresAt: number;
  tickRate: number;
  fly: FlyState;
}
export const volunteerCapacitySchema = z
  .object({
    type: z.literal('VOLUNTEER_CAPACITY'),
    capacity: z.number().int().min(0).max(3),
  })
  .strict();
const hostedStateSchema = stateMessageSchema.omit({ type: true, flyId: true }).extend({
  leaseId: z.string().uuid(),
  epoch: z.number().int().nonnegative(),
  flyId: z.string().max(80),
  action: z.enum(['FEED', 'DRINK']).optional(),
});
export type VolunteerState = z.infer<typeof hostedStateSchema>;
export const volunteerStatesSchema = z
  .object({
    type: z.literal('VOLUNTEER_STATES'),
    states: z.array(hostedStateSchema).max(3),
  })
  .strict();
export const actionMessageSchema = z
  .object({
    type: z.literal('FLY_ACTION'),
    action: z.enum(['FEED', 'DRINK']),
    timestamp: z.number().finite(),
  })
  .strict();
export const chatMessageSchema = z
  .object({
    type: z.literal('CHAT_SEND'),
    text: z
      .string()
      .trim()
      .min(1)
      .max(160)
      .regex(/^[^\u0000-\u001f\u007f]*$/),
  })
  .strict();
export const clientMessageSchema = z.discriminatedUnion('type', [
  stateMessageSchema,
  actionMessageSchema,
  bodyCheckpointSchema,
  chatMessageSchema,
  volunteerCapacitySchema,
  volunteerStatesSchema,
]);
export type ServerMessage =
  | {
      type: 'WELCOME';
      world: WorldState;
      fly: FlyState;
      events: FlyEvent[];
      chat: ChatMessage[];
      awaySince: number | null;
    }
  | { type: 'WORLD_STATE'; world: WorldState }
  | { type: 'WORLD_DELTA'; delta: WorldDelta }
  | { type: 'EVENT'; event: FlyEvent }
  | { type: 'EVENT_HISTORY'; events: FlyEvent[] }
  | { type: 'CHAT_MESSAGE'; message: ChatMessage }
  | { type: 'POINTS_UPDATE'; points: PointsLive }
  | { type: 'SIMULATION_LEASES'; leases: SimulationLease[] }
  | { type: 'SIMULATION_LEASE_REVOKED'; flyId: string; leaseId: string; reason: string }
  | { type: 'CORRECTION'; fly: FlyState; reason: string }
  | { type: 'ERROR'; message: string };
